pipeline {
    agent any

    stages {
        stage('Checkout SCM') {
            steps {
                script {
                    // Ensure you're checking out the correct branch
                    checkout scm
                }
            }
        }
        
        stage('Update Manifest') {
            environment {
                GIT_REPO_NAME = "flask-argocd-project"
            }
            steps {
                dir('Manifest-file') {
                    withVault(configuration: [
                        disableChildPoliciesOverride: false, 
                        timeout: 876, 
                        vaultCredentialId: 'vault-jenkins-roles', 
                        vaultUrl: 'http://3.82.220.45:8200'], 
                        vaultSecrets: [
                            [path: 'secrets/creds/my-secret-text', secretValues: [[vaultKey: 'github_username'], [vaultKey: 'github_password']]]]) {
                        
                        sh '''
                            # Configure Git
                            git config --global user.email "gerardambe@yahoo.com"
                            git config --global user.name "Gerardbulky"
        
                            # Extract and update image version in YML file
                            BUILD_NUMBER=${BUILD_NUMBER}
                            echo "Build Number: $BUILD_NUMBER"
                            
                            # Extract the current image tag
                            imageTag=$(grep -oP '(?<=image: bossmanjerry/flask-argocd-image:)[^ ]+' deployment-service.yml)
                            
                            # Debugging output
                            echo "Current Image Tag: $imageTag"
                            
                            # Replace the current image tag with the new BUILD_NUMBER
                            sed -i "s|image: bossmanjerry/flask-argocd-image:$imageTag|image: bossmanjerry/flask-argocd-image:${BUILD_NUMBER}|" deployment-service.yml
                            
                            # Confirm the change
                            echo "Updated Image Line:"
                            grep "image:" deployment-service.yml

                             # Commit and push changes to the `manifest-updates` branch
                            git add deployment-service.yml
                            git commit -m "Update deployment image to version ${BUILD_NUMBER}"

                            # Pull the latest changes from the remote `manifest-updates` branch to avoid non-fast-forward error
                            git pull origin manifest-updates --rebase

                            # Push the changes to the `manifest-updates` branch
                            git push https://${github_password}@github.com/${github_username}/${GIT_REPO_NAME}.git HEAD:manifest-updates
                        '''
                    }
                }
            }
        }

        stage('Auto Merge Manifest Updates') {
            steps {
                script {
                    // Checkout the main branch
                    sh 'git checkout main'
                    sh 'git pull origin main'

                    // Merge `manifest-updates` into `main`
                    sh 'git merge origin/manifest-updates --no-edit'

                    // Push the changes to the `main` branch
                    sh 'git push origin main'
                }
            }
        }
    }
}
